<?php

namespace ContainerBiJ83w3;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiUtilisateurControllerinscriptionUtilisateurService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.zlQAbiW.App\Controller\ApiUtilisateurController::inscriptionUtilisateur()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zlQAbiW.App\\Controller\\ApiUtilisateurController::inscriptionUtilisateur()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'roleRepo' => ['privates', 'App\\Repository\\RoleRepository', 'getRoleRepositoryService', true],
            'villeRepo' => ['privates', 'App\\Repository\\VilleRepository', 'getVilleRepositoryService', true],
        ], [
            'entityManager' => '?',
            'passwordHasher' => '?',
            'roleRepo' => 'App\\Repository\\RoleRepository',
            'villeRepo' => 'App\\Repository\\VilleRepository',
        ]))->withContext('App\\Controller\\ApiUtilisateurController::inscriptionUtilisateur()', $container);
    }
}
