<?php

namespace ContainerBiJ83w3;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiUtilisateurControllermodificationUtilisateurService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.sgBzxhs.App\Controller\ApiUtilisateurController::modificationUtilisateur()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sgBzxhs.App\\Controller\\ApiUtilisateurController::modificationUtilisateur()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'utilisateurRepo' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
            'villeRepo' => ['privates', 'App\\Repository\\VilleRepository', 'getVilleRepositoryService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'entityManager' => '?',
            'utilisateurRepo' => 'App\\Repository\\UtilisateurRepository',
            'villeRepo' => 'App\\Repository\\VilleRepository',
            'security' => '?',
        ]))->withContext('App\\Controller\\ApiUtilisateurController::modificationUtilisateur()', $container);
    }
}
