version: '3.7'

services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: "alanTuring2024!"
      MYSQL_DATABASE: "tima6358_amina_test"
    ports:
      - 3306:3306

  app:
    build:
      context: .
    environment:
      DATABASE_URL: "mysql://tima6358_amina_test:alanTuring2024!@mysql:3306/tima6358_amina_test"
    depends_on:
      - mysql
    ports:
      - 8080:80
