<?php

namespace ContainerDOl4LVz;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiReservationControllercreationReservationService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.o3SgjaL.App\Controller\ApiReservationController::creationReservation()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.o3SgjaL.App\\Controller\\ApiReservationController::creationReservation()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'utilisateurRepo' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
            'trajetRepo' => ['privates', 'App\\Repository\\TrajetRepository', 'getTrajetRepositoryService', true],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'entityManager' => '?',
            'utilisateurRepo' => 'App\\Repository\\UtilisateurRepository',
            'trajetRepo' => 'App\\Repository\\TrajetRepository',
            'validator' => '?',
        ]))->withContext('App\\Controller\\ApiReservationController::creationReservation()', $container);
    }
}
