<?php

namespace ContainerDOl4LVz;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiUtilisateurControllerlisteUtilisateursService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.d0o6gwo.App\Controller\ApiUtilisateurController::listeUtilisateurs()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.d0o6gwo.App\\Controller\\ApiUtilisateurController::listeUtilisateurs()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'utilisateurRepo' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
        ], [
            'utilisateurRepo' => 'App\\Repository\\UtilisateurRepository',
        ]))->withContext('App\\Controller\\ApiUtilisateurController::listeUtilisateurs()', $container);
    }
}
