<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDOl4LVz\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDOl4LVz/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerDOl4LVz.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerDOl4LVz\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerDOl4LVz\App_KernelTestDebugContainer([
    'container.build_hash' => 'DOl4LVz',
    'container.build_id' => 'c3785f91',
    'container.build_time' => 1741601680,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDOl4LVz');
