<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXRRDY0B\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXRRDY0B/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerXRRDY0B.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerXRRDY0B\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerXRRDY0B\App_KernelTestDebugContainer([
    'container.build_hash' => 'XRRDY0B',
    'container.build_id' => 'a662af54',
    'container.build_time' => 1741598103,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXRRDY0B');
