<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBiJ83w3\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBiJ83w3/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerBiJ83w3.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerBiJ83w3\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerBiJ83w3\App_KernelTestDebugContainer([
    'container.build_hash' => 'BiJ83w3',
    'container.build_id' => 'b0c2e2f2',
    'container.build_time' => 1741354987,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBiJ83w3');
