<?php

namespace ContainerXRRDY0B;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiUtilisateurControllerlisteRolesService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.qVVRW7Z.App\Controller\ApiUtilisateurController::listeRoles()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qVVRW7Z.App\\Controller\\ApiUtilisateurController::listeRoles()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'roleRepo' => ['privates', 'App\\Repository\\RoleRepository', 'getRoleRepositoryService', true],
        ], [
            'roleRepo' => 'App\\Repository\\RoleRepository',
        ]))->withContext('App\\Controller\\ApiUtilisateurController::listeRoles()', $container);
    }
}
