<?php

namespace ContainerXRRDY0B;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiVilleControllerajoutVilleService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.egipcEH.App\Controller\ApiVilleController::ajoutVille()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.egipcEH'] ?? $container->load('get_ServiceLocator_EgipcEHService'));

        if (isset($container->privates['.service_locator.egipcEH.App\\Controller\\ApiVilleController::ajoutVille()'])) {
            return $container->privates['.service_locator.egipcEH.App\\Controller\\ApiVilleController::ajoutVille()'];
        }

        return $container->privates['.service_locator.egipcEH.App\\Controller\\ApiVilleController::ajoutVille()'] = $a->withContext('App\\Controller\\ApiVilleController::ajoutVille()', $container);
    }
}
