<?php

namespace ContainerAB0jQZ5;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiTrajetControllerlisteTrajetsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dlWO762.App\Controller\ApiTrajetController::listeTrajets()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dlWO762.App\\Controller\\ApiTrajetController::listeTrajets()'] = ($container->privates['.service_locator.dlWO762'] ?? $container->load('get_ServiceLocator_DlWO762Service'))->withContext('App\\Controller\\ApiTrajetController::listeTrajets()', $container);
    }
}
