<?php

namespace ContainerAB0jQZ5;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiTrajetControllersuppressionTrajetService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BM8acBv.App\Controller\ApiTrajetController::suppressionTrajet()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BM8acBv.App\\Controller\\ApiTrajetController::suppressionTrajet()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'trajetRepository' => ['privates', 'App\\Repository\\TrajetRepository', 'getTrajetRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'trajetRepository' => 'App\\Repository\\TrajetRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\ApiTrajetController::suppressionTrajet()', $container);
    }
}
