<?php

namespace ContainerAB0jQZ5;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiReservationControllerannulerReservationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MpimfDU.App\Controller\ApiReservationController::annulerReservation()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MpimfDU.App\\Controller\\ApiReservationController::annulerReservation()'] = ($container->privates['.service_locator.MpimfDU'] ?? $container->load('get_ServiceLocator_MpimfDUService'))->withContext('App\\Controller\\ApiReservationController::annulerReservation()', $container);
    }
}
